# Run commitlint on the commit messages in a pull request.

name: Lint Commit Messages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
    - '**'

jobs:
  commitlint:
    uses: openedx/.github/.github/workflows/commitlint.yml@master
