name: Git tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]


jobs:
  git-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: ubuntu-22.04 default git
            os: ubuntu-22.04
            git_version: default

          - name: ubuntu-20.04 default git
            os: ubuntu-20.04
            git_version: default

          - name: ubuntu-22.04 @ v2.40.0
            os: ubuntu-22.04
            git_version: 2.40.0

          - name: ubuntu-20.04 @ v2.40.0
            os: ubuntu-20.04
            git_version: 2.40.0

          - name: ubuntu-20.04 @ v2.25.0
            os: ubuntu-20.04
            git_version: 2.25.0
    steps:
    - name: install custom version of git
      run: |
        wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-${{ matrix.git_version }}.tar.gz
        tar -xzf git-${{ matrix.git_version }}.tar.gz
        cd git-${{ matrix.git_version }}
        make configure
        ./configure --prefix=/usr/local
        make all
        sudo make install

      if: matrix.git_version != 'default'

    - name: print git version
      run: git --version

    - name: install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: install shellspec
      run: |
        brew tap shellspec/shellspec
        brew install shellspec
    - name: install getoptions
      run: |
        brew tap ko1nksm/getoptions
        brew install getoptions

    - uses: actions/checkout@v3
    - name: run integration tests
      run: make performance_tests
