name: Git tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]


jobs:
  git-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: ubuntu-22.04 default git
            os: ubuntu-22.04
            git_version: default

          - name: ubuntu-20.04 default git
            os: ubuntu-20.04
            git_version: default

          - name: ubuntu-22.04 @ v2.40.0
            os: ubuntu-22.04
            git_version: 2.40.0

          - name: ubuntu-20.04 @ v2.40.0
            os: ubuntu-20.04
            git_version: 2.40.0

          - name: ubuntu-20.04 @ v2.25.0
            os: ubuntu-20.04
            git_version: 2.25.0
    steps:
    - name: install custom version of git
      run: |
        wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-${{ matrix.git_version }}.tar.gz
        tar -xzf git-${{ matrix.git_version }}.tar.gz
        cd git-${{ matrix.git_version }}
        make configure
        ./configure --prefix=/usr/local
        make all
        sudo make install

      if: matrix.git_version != 'default'

    - name: print git version
      run: git --version

    - name: install shellspec
      run: curl -fsSL https://git.io/shellspec | sh

    - name: install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: install getoptions and gengetoptions
      run: |
        wget https://github.com/ko1nksm/getoptions/releases/download/latest/getoptions -O /usr/local/bin/getoptions
        wget https://github.com/ko1nksm/getoptions/releases/download/latest/gengetoptions -O /usr/local/bin/gengetoptions
        chmod +x /usr/local/bin/getoptions /usr/local/bin/gengetoptions

    - uses: actions/checkout@v3
    - name: run integration tests
      run: make performance_tests
